name: build

on:
  push:

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-i686, linux-riscv64, linux-x86_64]
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          dpf_path: ./deps/dpf
          lto: true

  macos:
    strategy:
      matrix:
        target: [macos-intel]
        # TODO needs fixing
        # , macos-universal
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          dpf_path: ./deps/dpf
          # lto: true

  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/cache@v4
        with:
          path: emsdk
          key: emsdk
      - name: Build for wasm
        run: ./build-for-wasm.sh
      - name: Set sha8
        run: echo "SHA8=$(echo ${{ github.sha }} | cut -c1-8)" >> $GITHUB_ENV
      - name: Set basenames
        run: echo "ARTIFACT_BASENAME=BigBlueBetterAudio-wasm-${{ github.event.pull_request.number || env.SHA8 }}" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_BASENAME }}
          path: |
            bin/BBBA-mapi.*
            bin-nosimd/BBBA-mapi-nosimd.*

  windows:
    strategy:
      matrix:
        target: [win32, win64]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: ${{ matrix.target }}
          dpf_path: ./deps/dpf

  pluginval:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: distrho/dpf-makefile-action@v1
        with:
          target: pluginval
          dpf_path: ./deps/dpf
